//! Output module that provides "tee" functionality - writing to both stdout/stderr and a log file.
//!
//! When a log file is initialized, ALL stdout and stderr output (including from dependencies)
//! will be written to both the terminal and the log file (in append mode).
//!
//! This works by redirecting stdout/stderr file descriptors to pipes, then spawning
//! background threads that read from the pipes and write to both destinations.
//!
//! AI-ORIGIN: This file was generated by AI/LLM, but reviewed, tested, and corrected by the
//! maintainer. See AI_POLICY.md for more info.

use std::fs::{File, OpenOptions};
use std::io::{self, Read, Write};
use std::path::Path;
use std::sync::{Arc, Mutex};
use std::thread::{self, JoinHandle};

use filedescriptor::{FileDescriptor, Pipe, StdioDescriptor};

/// Guard for the tee output system.
/// When dropped, flushes all pending output and waits for tee threads to complete.
pub struct TeeGuard {
    stdout_handle: Option<JoinHandle<()>>,
    stderr_handle: Option<JoinHandle<()>>,
    original_stdout: Option<FileDescriptor>,
    original_stderr: Option<FileDescriptor>,
}

impl Drop for TeeGuard {
    fn drop(&mut self) {
        // Flush stdout and stderr to push data through the pipes
        let _ = io::stdout().flush();
        let _ = io::stderr().flush();

        // Restore original stdout/stderr - this closes the pipe write ends
        // which signals EOF to the tee threads
        if let Some(fd) = self.original_stdout.take() {
            let _ = FileDescriptor::redirect_stdio(&fd, StdioDescriptor::Stdout);
        }
        if let Some(fd) = self.original_stderr.take() {
            let _ = FileDescriptor::redirect_stdio(&fd, StdioDescriptor::Stderr);
        }

        // Wait for tee threads to finish processing remaining data
        if let Some(handle) = self.stdout_handle.take() {
            let _ = handle.join();
        }
        if let Some(handle) = self.stderr_handle.take() {
            let _ = handle.join();
        }
    }
}

/// Spawn a tee thread for one stdio stream.
fn spawn_tee_thread(
    mut pipe_read: FileDescriptor,
    mut original_fd: FileDescriptor,
    log_file: Arc<Mutex<File>>,
) -> JoinHandle<()> {
    thread::spawn(move || {
        let mut buffer = [0u8; 4096];
        loop {
            match pipe_read.read(&mut buffer) {
                Ok(0) => break, // EOF - pipe closed
                Ok(n) => {
                    let data = &buffer[..n];

                    // Write to original fd (terminal)
                    let _ = original_fd.write_all(data);
                    let _ = original_fd.flush();

                    // Write to log file
                    if let Ok(mut file) = log_file.lock() {
                        let _ = file.write_all(data);
                        let _ = file.flush();
                    }
                }
                Err(ref e) if e.kind() == io::ErrorKind::Interrupted => continue,
                Err(_) => break,
            }
        }
    })
}

/// Initialize tee output to a file. All subsequent stdout and stderr output will be written
/// to both the terminal and the specified file (in append mode).
///
/// Returns a guard that must be held until the end of main() to ensure all output is captured.
/// When the guard is dropped, it will flush all pending output and wait for the tee threads.
pub fn init_log_file<P: AsRef<Path>>(path: P) -> io::Result<TeeGuard> {
    let mut log_file = OpenOptions::new().create(true).append(true).open(path)?;

    // Write a separator before each run
    log_file.write_all(b"\n---\n")?;
    log_file.flush()?;

    let log_file = Arc::new(Mutex::new(log_file));

    // Set up stdout tee
    let stdout_pipe = Pipe::new().map_err(|e| io::Error::new(io::ErrorKind::Other, e))?;
    let original_stdout =
        FileDescriptor::redirect_stdio(&stdout_pipe.write, StdioDescriptor::Stdout)
            .map_err(|e| io::Error::new(io::ErrorKind::Other, e))?;
    let stdout_handle = spawn_tee_thread(
        stdout_pipe.read,
        original_stdout
            .try_clone()
            .map_err(|e| io::Error::new(io::ErrorKind::Other, e))?,
        Arc::clone(&log_file),
    );

    // Set up stderr tee
    let stderr_pipe = Pipe::new().map_err(|e| io::Error::new(io::ErrorKind::Other, e))?;
    let original_stderr =
        FileDescriptor::redirect_stdio(&stderr_pipe.write, StdioDescriptor::Stderr)
            .map_err(|e| io::Error::new(io::ErrorKind::Other, e))?;
    let stderr_handle = spawn_tee_thread(
        stderr_pipe.read,
        original_stderr
            .try_clone()
            .map_err(|e| io::Error::new(io::ErrorKind::Other, e))?,
        Arc::clone(&log_file),
    );

    Ok(TeeGuard {
        stdout_handle: Some(stdout_handle),
        stderr_handle: Some(stderr_handle),
        original_stdout: Some(original_stdout),
        original_stderr: Some(original_stderr),
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use serial_test::serial;
    use std::fs;
    use std::io::Write;
    use std::os::unix::io::FromRawFd;

    // NOTE: Rust's test harness captures stdout/stderr at a level above the file
    // descriptor, so println!/eprintln! don't actually write to fd 1/2 during tests.
    // We use raw fd writes in these tests to verify the tee functionality works correctly.
    // In real programs (not under test harness), println!/eprintln! work as expected.

    fn read_log_file(path: &Path) -> String {
        fs::read_to_string(path).unwrap_or_default()
    }

    /// Write directly to a file descriptor, bypassing Rust's stdout/stderr.
    fn write_to_fd(fd: i32, msg: &[u8]) {
        unsafe {
            let mut f = std::fs::File::from_raw_fd(fd);
            f.write_all(msg).unwrap();
            f.flush().unwrap();
            std::mem::forget(f); // Don't close the fd
        }
    }

    fn write_to_stdout(msg: &[u8]) {
        write_to_fd(1, msg);
    }

    fn write_to_stderr(msg: &[u8]) {
        write_to_fd(2, msg);
    }

    #[test]
    #[serial]
    fn test_stdout_captured() {
        let dir = tempfile::tempdir().unwrap();
        let log_path = dir.path().join("test.log");

        {
            let _guard = init_log_file(&log_path).unwrap();
            write_to_stdout(b"hello stdout");
        }

        let contents = read_log_file(&log_path);
        assert!(
            contents.contains("hello stdout"),
            "stdout not captured: {}",
            contents
        );
    }

    #[test]
    #[serial]
    fn test_stderr_captured() {
        let dir = tempfile::tempdir().unwrap();
        let log_path = dir.path().join("test.log");

        {
            let _guard = init_log_file(&log_path).unwrap();
            write_to_stderr(b"hello stderr");
        }

        let contents = read_log_file(&log_path);
        assert!(
            contents.contains("hello stderr"),
            "stderr not captured: {}",
            contents
        );
    }

    #[test]
    #[serial]
    fn test_both_streams_captured() {
        let dir = tempfile::tempdir().unwrap();
        let log_path = dir.path().join("test.log");

        {
            let _guard = init_log_file(&log_path).unwrap();
            write_to_stdout(b"from stdout");
            write_to_stderr(b"from stderr");
        }

        let contents = read_log_file(&log_path);
        assert!(
            contents.contains("from stdout"),
            "stdout not captured: {}",
            contents
        );
        assert!(
            contents.contains("from stderr"),
            "stderr not captured: {}",
            contents
        );
    }

    #[test]
    #[serial]
    fn test_separator_written() {
        let dir = tempfile::tempdir().unwrap();
        let log_path = dir.path().join("test.log");

        {
            let _guard = init_log_file(&log_path).unwrap();
        }

        let contents = read_log_file(&log_path);
        assert!(
            contents.contains("\n---\n"),
            "separator not found: {}",
            contents
        );
    }

    #[test]
    #[serial]
    fn test_reinitialize_after_drop() {
        let dir = tempfile::tempdir().unwrap();
        let log_path = dir.path().join("test.log");

        // First initialization
        {
            let _guard = init_log_file(&log_path).unwrap();
            write_to_stdout(b"first run\n");
        }

        // Second initialization after drop
        {
            let _guard = init_log_file(&log_path).unwrap();
            write_to_stdout(b"second run\n");
        }

        let contents = read_log_file(&log_path);
        assert!(
            contents.contains("first run"),
            "first run not captured: {}",
            contents
        );
        assert!(
            contents.contains("second run"),
            "second run not captured: {}",
            contents
        );

        // Should have two separators
        let separator_count = contents.matches("\n---\n").count();
        assert_eq!(
            separator_count, 2,
            "expected 2 separators, found {}: {}",
            separator_count, contents
        );
    }

    #[test]
    #[serial]
    fn test_append_mode() {
        let dir = tempfile::tempdir().unwrap();
        let log_path = dir.path().join("test.log");

        // Write some initial content
        fs::write(&log_path, "initial content\n").unwrap();

        {
            let _guard = init_log_file(&log_path).unwrap();
            write_to_stdout(b"appended content\n");
        }

        let contents = read_log_file(&log_path);
        assert!(
            contents.starts_with("initial content\n"),
            "initial content lost: {}",
            contents
        );
        assert!(
            contents.contains("appended content"),
            "appended content not found: {}",
            contents
        );
    }

    #[test]
    #[serial]
    fn test_output_not_captured_after_drop() {
        let dir = tempfile::tempdir().unwrap();
        let log_path = dir.path().join("test.log");

        {
            let _guard = init_log_file(&log_path).unwrap();
            write_to_stdout(b"during tee\n");
        }

        // This should not be captured after the guard is dropped
        write_to_stdout(b"after tee\n");

        let contents = read_log_file(&log_path);
        assert!(
            contents.contains("during tee"),
            "output during tee not captured"
        );
        assert!(
            !contents.contains("after tee"),
            "output after tee should not be captured"
        );
    }
}
